# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: "14-backend-pitest: Java Mutation Testing (Pitest)"

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths: [src/**, pom.xml, lombok.config, .github/workflows/14-backend-pitest.yml]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v3.5.2
     
    - name: Set up Java (version from .java-version file)
      uses: actions/setup-java@v3
      with:
         distribution: semeru # See: https://github.com/actions/setup-java#supported-distributions
         java-version-file: ./.java-version
    - name: Build with Maven
      run: mvn -B test 
    
    # Note that we DO NOT download history in this job;
    # this job is intended as a "reset" of the history for the main
    # branch each time the main branch changes

    - name: Pitest
      run: mvn test org.pitest:pitest-maven:mutationCoverage -DmutationThreshold=100 
    - name: Upload Pitest History to Artifacts
      if: always() # always upload artifacts, even if tests fail
      uses: actions/upload-artifact@v3.1.2
      with:
        name: pitest-main-history.bin
        path: target/pit-history/history.bin
    - name: Upload Pitest to Artifacts
      if: always() # always upload artifacts, even if tests fail
      uses: actions/upload-artifact@v3.1.2
      with:
        name: pitest
        path: target/pit-reports/* 
    - name: Deploy ðŸš€
      if: always() # always upload artifacts, even if tests fail
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: target/pit-reports # The folder where the files we want to publish are located
        clean: true # Automatically remove deleted files from the deploy branch
        target-folder: pitest # The folder that we serve our files from