name: "33-frontend-incremental-mutation-testing: Stryker JS Mutation Testing (JavaScript/Jest)"

# This workflow pulls incremental mutation testing results
# if they exist for the named branch, and then 
# uses those incremental results to run mutation testing faster.
# Reference: https://stryker-mutator.io/docs/stryker-js/incremental/

on:
  workflow_dispatch:
  pull_request:
    paths: [frontend/**]
  push:
    branches: [main]
    paths: [frontend/**]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 40

    steps:
      - uses: szenius/set-timezone@v1.2
        with:
          timezoneLinux: "America/Los_Angeles"
      - uses: actions/checkout@v3.5.2
        with: 
          fetch-depth: 2
      - name: Setup Node.js
        uses: actions/setup-node@v3.6.0
        with:
          node-version-file: 'frontend/package.json'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      - name: Figure out Branch nam
        id: get-branch-name
        run: | 
            GITHUB_HEAD_REF="${GITHUB_HEAD_REF}"
            echo GITHUB_HEAD_REF=${GITHUB_HEAD_REF}
            GITHUB_REF_CLEANED=${GITHUB_REF/refs\/heads\//}
            echo GITHUB_REF_CLEANED=${GITHUB_REF_CLEANED}
            GITHUB_REF_CLEANED=${GITHUB_REF_CLEANED//\//-}
            echo GITHUB_REF_CLEANED=${GITHUB_REF_CLEANED}
            BRANCH="${GITHUB_HEAD_REF:-${GITHUB_REF_CLEANED}}"
            echo "branch_name=${BRANCH}"
            echo "branch_name=${BRANCH}" >> "$GITHUB_ENV"    
      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2.27.0
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          branch: ${{ env.branch_name }}
          name: stryker-incremental-${{env.branch_name}}.json
          path: frontend/reports
          check_artifacts: true
          if_no_artifact_found: warn
      - name: Debugging output one
        run: |
          ls -lRt frontend
      - run: npm ci
        working-directory: ./frontend
      - run: npx stryker run --incremental --incrementalFile reports/stryker-incremental-${{env.branch_name}}.json
        working-directory: ./frontend

      - name: Debugging output two
        run: |
          ls -lRt frontend

      - name: Upload stryker incremental file to Artifacts
        uses: actions/upload-artifact@v3.1.2
        with:
          name: stryker-incremental-${{env.branch_name}}.json
          path: frontend/reports/stryker-incremental-${{env.branch_name}}.json

      - name: Upload stryker report to Artifacts
        if: always() # always upload artifacts, even if tests fail
        uses: actions/upload-artifact@v3.1.2
        with:
          name: stryker-report
          path: frontend/reports/mutation/*

      - name: Get PR number
        id: get-pr-num
        run: |
          echo "GITHUB_EVENT_PATH=${GITHUB_EVENT_PATH}"
          pr_number=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          echo "pr_number=${pr_number}" 
          echo "pr_number=${pr_number}" >> "$GITHUB_ENV"
      - name: Figure out Branch name
        id: get-branch-name
        run: | 
            GITHUB_HEAD_REF="${GITHUB_HEAD_REF}"
            echo GITHUB_HEAD_REF=${GITHUB_HEAD_REF}
            GITHUB_REF_CLEANED=${GITHUB_REF/refs\/heads\//}
            echo GITHUB_REF_CLEANED=${GITHUB_REF_CLEANED}
            GITHUB_REF_CLEANED=${GITHUB_REF_CLEANED//\//-}
            echo GITHUB_REF_CLEANED=${GITHUB_REF_CLEANED}
            BRANCH="${GITHUB_HEAD_REF:-${GITHUB_REF_CLEANED}}"
            echo "branch_name=${BRANCH}"
            echo "branch_name=${BRANCH}" >> "$GITHUB_ENV"