name: "36-frontend-eslint: JavaScript style checking"

on:
  workflow_dispatch:
  pull_request:
    paths: [frontend/**]
  push:
    branches: [main]
    paths: [frontend/**]

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: szenius/set-timezone@v1.2
        with:
          timezoneLinux: "America/Los_Angeles"
      - uses: actions/checkout@v3.5.2
        with: 
          fetch-depth: 2
      - name: Setup Node.js
        uses: actions/setup-node@v3.6.0
        with:
          node-version-file: 'frontend/package.json'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      - run: npm ci
        working-directory: ./frontend
      - run: npx eslint --max-warnings 0 .
        working-directory: ./frontend
