# Creates/Resets the gh-pages branch to the intended start state

name: "52-storybook-main-branch: Update storybook when main branch changes"
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'

env:
  GH_TOKEN: ${{ github.token }}

permissions:
  contents: write
  pages: write
  id-token: write

jobs: 
  build-storybook-main:
    name: Storybook (main branch)
    runs-on: ubuntu-latest

    steps:
    - name: Checkout local code to establish repo
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json

    - name: Build Storybook for main branch
      working-directory: frontend
      run: | # Install npm packages and build the Storybook files
        npm install
        npx build-storybook --docs -o storybook_static

    - name: Deploy ðŸš€
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: frontend/storybook_static # The folder that the build-storybook script generates files.
        clean: true # Automatically remove deleted files from the deploy branch
        target-folder: storybook # The folder that we serve our Storybook files from
   
