
name: Publish docs (Storybook) to GitHub Pages QA
on: 
  pull_request:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ðŸ›Žï¸
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
      - name: Append name of site to _config.yml
        working-directory: ./frontend/docs-qa-index
        run: | 
          OWNER_PLUS_REPOSITORY=${{github.repository}}
          OWNER=${{ github.repository_owner }}
          REPOSITORY=${OWNER_PLUS_REPOSITORY/$OWNER\//}
          echo "repo: ${OWNER_PLUS_REPOSITORY}" >> _config.yml
          echo "owner: ${OWNER}" >> _config.yml
          echo "repo_name: ${REPOSITORY}" >> _config.yml
      - name: Deploy index.md and jekyll files for docs-qa site ðŸš€
        uses: JamesIves/github-pages-deploy-action@4.2.0
        with:
          repository-name: ${{ github.repository }}-docs-qa
          token: ${{ secrets.DOCS_TOKEN }}
          branch: main # The branch the action should deploy to.
          folder: frontend/docs-qa-index 
          clean: false 
          target-folder: docs
      - name: Generate .md file to add to branch collection
        working-directory: ./frontend
        run: | 
          BRANCH_DIR=_branches.tmp
          mkdir -p $BRANCH_DIR
          FILENAME=${BRANCH_DIR}/${{github.head_ref }}.md
          rm -f $FILENAME
          touch $FILENAME
          echo "---" >> $FILENAME
          echo "name: ${{ github.head_ref }}" >> $FILENAME
          echo "actor: ${{ github.actor}}" >> $FILENAME
          echo "pull_request_url: ${{ github.event.pull_request.html_url}}" >> $FILENAME
          echo "pull_request_num: ${{ github.event.pull_request.number}}" >> $FILENAME
          echo "---" >> $FILENAME
      # - name: Deploy (branch-name).md file to branch collection ðŸš€
      #   uses: JamesIves/github-pages-deploy-action@4.2.0
      #   with:
      #     repository-name: ${{ github.repository }}-docs-qa
      #     token: ${{ secrets.DOCS_TOKEN }}
      #     branch: main # The branch the action should deploy to.
      #     folder: frontend/_branches.tmp # The folder that the build-storybook script generates files.
      #     clean: false # Automatically remove deleted files from the deploy branch
      #     target-folder: docs/_branches
      - name: Pushes branch
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.DOCS_TOKEN }}
        with:
          source_file: 'frontend/_branches.tmp/${{github.head_ref }}.md'
          destination_repo: ${{ github.repository }}-docs-qa
          destination_folder: 'docs/_branches'
          commit_message: 'Add branch ${{ github.head_ref }} to docs-qa repo'
          user_email: phtcon@ucsb.edu
          user_name: "Phill Conrad, UCSB CS machine user"
      - name: Install and Build ðŸ”§
        working-directory: ./frontend
        run: | # Install npm packages and build the Storybook files
          npm install
          mkdir -p storybook-static
          npm run build-storybook
      - name: Deploy ðŸš€
        uses: JamesIves/github-pages-deploy-action@4.2.0
        with:
          repository-name: ${{ github.repository }}-docs-qa
          token: ${{ secrets.DOCS_TOKEN }}
          branch: main # The branch the action should deploy to.
          folder: frontend/storybook-static # The folder that the build-storybook script generates files.
          clean: true # Automatically remove deleted files from the deploy branch
          target-folder: docs/storybook-qa/${{ github.head_ref}} # The folder that we serve our Storybook files from 
      
