
name: Publish docs (Storybook) to GitHub Pages QA
on: 
  pull_request:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
      - name: Install and Build ğŸ”§
        working-directory: ./frontend
        run: | # Install npm packages and build the Storybook files
          npm install
          mkdir -p storybook-static
          npm run build-storybook
      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@4.2.0
        with:
          repository-name: ${{ github.repository }}-docs-qa
          token: ${{ secrets.TOKEN }}
          branch: main # The branch the action should deploy to.
          folder: frontend/storybook-static # The folder that the build-storybook script generates files.
          clean: true # Automatically remove deleted files from the deploy branch
          target-folder: docs/storybook # The folder that we serve our Storybook files from 
